config/routes.rb
Rails.application.routes.draw do

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: "posts#index"
devise_for :users,
path: '',
path_names: {sign_in: 'login', sign_out: 'logout', edit:'profile',sign_up: 'registration'}
# controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
resources :users, only: [:show, :index, :destroy]
resources :friendships


authenticated :user do
    root 'posts#index', as: :authenticated_root
    end 
resources :posts  do
    resource :like, module: :posts
   
end

resources :posts do
    resource :comments
end
  
resources :users do
    resources :friendships
    delete 'reject_request', to: 'friendships#destroy'
    post 'accept_request', to: 'friendships#update'
  end

resources :users  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :body, presence: true, length: { minimum: 5, maximum: 500 }
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  def create
    @post.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def destroy
    @post.likes.where(user_id: current_user.id).destroy_all
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  # GET /posts.json
  def index
    # @posts = Post.where(user: current_user).or(Post.where(user: @friends))
    @posts = current_user.user_page.all.order('created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new(post: @post)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = 'Post was successfully created'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_likes.html.erb
<% if user_signed_in? && current_user.likes?(post) %>
   <%= link_to 'Unlike', post_like_path(post), method: :delete %>
<%else%>
    <%= link_to 'Like', post_like_path(post), method: :post %>
<%end%>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
<h2>TEST CONTENT</h2>
    <div class="row">
        <p id="notice"><%= notice %></p>
        <div class="center jumbotron main-banner">
            <div class="user-photo">
                <img class="user-gravatar" alt="User photo" src="/assets/underwater" />
                <h2><%= current_user.username %></h2> 
                </div>
                    <div class="under-buner-menu">
                    <a href="#">Lorem</a>
                    <a href="#">Ipsum</a>
                    <a href="#">Set</a>
                    <a href="#">Loram</a>
                </div>
           </div>
        </div>

      <div>
        <ul>
          <li class="header-styles">
          <%= link_to 'See All Users', users_path, :class => 'users-styles-a' %>
          </li>
          <li class="header-styles">
          <%= link_to 'View All Posts ', posts_path,:class => 'users-styles-a' %>
          </li>
        </ul>
      </div>
<hr>
 <div> 
   <p>Create a new post here...</p> 
  <button class='btn btn-primary'>
    <%= link_to 'New Post', new_post_path %>
  </button>
</div>  
<h1 class='posts-header'> All Posts</h1>
    <% @posts.each do |post| %>
      <div class="card ">

      <div class="card-body info">
        <p>Author: <%= post.user.username %> </p> 
        <p>Date: <%= post.created_at.to_formatted_s(:short) %> UTC </p> 
      </div>

        <div class="card-body">
          <p class="card-text"><%= post.body %></p> 
        </div>  
         
       
            <div>
            <% if current_user == post.user %>
            <button class='btn btn-primary'><%= link_to 'Show', post %></button>
            <button class='btn btn-primary'><%= link_to 'Edit', edit_post_path(post) %></button>
            <button class='btn btn-primary'><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            <% end %>
            </div>
            <hr>
            <div>
<td><%= render partial: "likes", locals: {post: post}%></td> 
<td><i class="fa fa-thumbs-up"></i><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></td><hr>
<span class='comment-count'>Comments: <%= post.comments.count =%> </span>
</div>

       
          <div class='card-body'> <br>
            <%= render "comment/form" ,post: post=%>  
          </div>
          
          <% post.comments.each do |comment| %>
          <div class='comments'>   
          <div class='card-body left'>  
          <ol class='posts'>
          <%= render 'comment/comment', comment: comment,post: post %>
          </ol>
          </div>
          
          </div>
      <% end %>
      </div>
    <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%=render "layouts/header" %>

<p id="notice"><%= notice %></p>


<p>
  <strong>Post:</strong>
  <%= @post.body %>
   
</p>
<div class= "col-lg-12">
<%= link_to 'Back to Main', posts_path %>
</div>