config/routes.rb
Rails.application.routes.draw do

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: "posts#index"
devise_for :users,
path: '',
path_names: {sign_in: 'login', sign_out: 'logout', edit:'profile',sign_up: 'registration'}
# controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
resources :users, only: [:show, :index, :destroy]
resources :friendships


authenticated :user do
    root 'posts#index', as: :authenticated_root
    end 
resources :posts  do
    resource :like, module: :posts
   
end

resources :posts do
    resource :comments
end
  
resources :users do
    resources :friendships
    delete 'reject_request', to: 'friendships#destroy'
    post 'accept_request', to: 'friendships#update'
  end

resources :users  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
   <div class="container">
   <%= link_to "facebook-clone", '/', id: "logo"%>
   <nav>
    <ul class="nav navbar-nav navbar-right">
<% if user_signed_in? %>
<li class="header-styles">
<i class="fa fa-user"></i>
  Logged in as: <strong><%= current_user.username %></strong>
</li>
<li class="header-styles">
          <% if current_user.friendship_requests.count > 0 %>
            <%= link_to "You have #{pluralize(current_user.friendship_requests.count, 'Friend Request')}", user_friendships_path(current_user), class: "header-styles-a" %>
          <% else %>
            <%= link_to "You have #{pluralize(current_user.friends.count, 'Friend')}", user_friendships_path(current_user), class: "header-styles-a" %>
          <% end %>
        </li>

<li class="header-styles">
  <%= link_to 'Edit profile |', edit_user_registration_path, class: 'header-styles-a' %> 
  </li>
<li class="header-styles">
  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'header-styles-a'  %>
</li>
<% else %>
<li class="header-styles">
  <%= link_to "Sign up |", new_user_registration_path, :class => 'header-styles-a'  %>
  </li>
  <li class="header-styles">
  <%= link_to "Login", new_user_session_path, :class => 'header-styles-a'  %>
  </li>
<% end %>

    </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
     <p class ="notice"><%= notice %></p>
     <p class ="alert"><%= alert %></p>
      <%= yield %>
   
    <%= render 'layouts/footer' %>
  </body>
</html>